=head1 NAME

Web::DOM::ChildNode - The DOM |ChildNode| object

=head1 DESCRIPTION

The C<Web::DOM::ChildNode> class implements the DOM C<ChildNode>
interface.  The C<Web::DOM::ChildNode> class is an abstract class.  It
is used as subclasses such as C<Web::DOM::Element> and
C<Web::DOM::Text>.

=head1 METHODS

=over 4

=item $sibling = $node->next_element_sibling

Return the next element sibling.  If there is no such node, C<undef>
is returned.  [DOM]

=item $sibling = $node->previous_element_sibling

Return the previous element sibling.  If there is no such node,
C<undef> is returned.  [DOM]

=back

=head1 SPECIFICATION

=over 4

=item DOM

DOM Living Standard <http://dom.spec.whatwg.org/#interface-childnode>.

=back

=head1 SEE ALSO

L<Web::DOM::Element>, L<Web::DOM::CharacterData>,
L<Web::DOM::DocumentType>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2012 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
