=head1 NAME

Web::DOM::DocumentType - The DOM |DocumentType| object

=head1 DESCRIPTION

The C<Web::DOM::DocumentType> class implements the DOM C<DocumentType>
interface.

=head1 METHODS

In addition to the methods of classes L<Web::DOM::Node> and
L<Web::DOM::ChildNode>, following methods are available:

=over 4

=item $name = $dt->name

Return the name of the document type.  [DOM]

=item $id = $dt->public_id

=item $dt->public_id ($id)

Return or set the public identifier of the document type.  [DOM]
[MANAKAI]

=item $id = $dt->system_id

=item $dt->system_id ($id)

Return or set the system identifier of the document type.  [DOM]
[MANAKAI]

=back

=head1 SPECIFICATIONS

=over 4

=item DOM

DOM Living Standard
<http://dom.spec.whatwg.org/#interface-documenttype>.

=item MANAKAI

manakai DOM Extensions
<http://suika.fam.cx/~wakaba/wiki/sw/n/manakai%20DOM%20Extensions>.

=back

=head1 SEE ALSO

L<Web::DOM::Node>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2012 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
