=head1 NAME

Web::DOM::Element - The DOM |Element| object

=head1 DESCRIPTION

The C<Web::DOM::Element> class implements the DOM C<Element>
interface.

=head1 METHODS

In addition to the methods of classes L<Web::DOM::Node>,
L<Web::DOM::RootNode>, and L<Web::DOM::ChildNode>, following methods
are available:

=over 4

=item $value = $el->get_attribute ($name)

Return the value of the specified attribute.  If there is no attribute
with the specified name, C<undef> is returned.  [DOM]

=item $value = $el->get_attribute_ns ($nsurl, $local_name)

Return the value of the attribute with the specified namespace URL and
local name.  If there is no attribute with the specified name,
C<undef> is returned.  [DOM]

=item $name = $el->local_name

Return the local name of the element.  [DOM]

=item $name = $el->manakai_local_name

Return the local name of the element.  This method is deprecated in
favor of C<local_name>. [MANAKAI]

=item $url = $el->namespace_uri

Return the namespace URL of the element.  [DOM]

=item $prefix = $el->prefix

=item $el->prefix ($prefix)

If no argument is specified, return the namespace prefix of the
element, if any, or C<undef>.  [DOM]

If the argument is specified, the value is set as the namespace prefix
of the element.  If the value is C<undef>, the namespace prefix is
removed.  [MANAKAI]

=item $el->set_attribute ($name => $value)

Set the attribute with the specified name and value.  If there is
already the attribute with the same name, its value is replaced by the
new one.  [DOM]

=item $el->set_attribute_ns ($nsurl, $local_name => $value)

Set the attribute with the specified namespace URL, local name, and
value.  If there is already the attribute with the same namespace URL
/ local name pair, its value is replaced by the new one.  [DOM]

=item $name = $el->tag_name

Return the tag name of the element.  [DOM]

=back

=head1 SPECIFICATIONS

=over 4

=item DOM

DOM Living Standard <http://dom.spec.whatwg.org/#interface-element>.

=item MANAKAI

manakai DOM Extensions
<http://suika.fam.cx/~wakaba/wiki/sw/n/manakai%20DOM%20Node%20Extensions>.

=back

=head1 SEE ALSO

L<Web::DOM::Node>, L<Web::DOM::Attr>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2012 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
