=head1 NAME

Web::DOM::NamedNodeMap - The DOM |NamedNodeMap| object

=head1 DESCRIPTION

The C<Web::DOM::NamedNodeMap> class implements the DOM C<NamedNodeMap>
interface.

=head1 METHODS

Following methods are available:

=over 4

=item $node = $col->get_named_item ($name)

Return the first node in the list whose name is equal to the argument.
[DOMATTREXODUS] [DOM3CORE]

=item $node = $col->get_named_item_ns ($nsurl, $local_name)

Return the node in the list whose namespace URL and local name are
equal to the arguments.  [DOMATTREXODUS] [DOM3CORE]

=item $node = $col->[$index]

=item $node = $col->item ($index)

Return the node in the collection, specified by its index.
[DOMATTREXODUS] [DOM3CORE] [DOMPERL]

Use of the C<item> method is discouraged as it doesn't support Perlish
ways to access items, such as negative indexing, while C<< $col->[-1]
>> works as you intended.

=item $number = @$col

=item $number = $col->length

Return the number of the nodes in the collection.  [DOMATTREXODUS]
[DOM3CORE] [DOMPERL]

=item $node = $col->remove_named_item ($name)

Remove the first node in the list whose name is equal to the argument.
The removed node is returned.  [DOMATTREXODUS] [DOM3CORE]

=item $node = $col->remove_named_item_ns ($nsurl, $local_name)

Remove the node in the list whose namespace URL and local name are
equal to the arguments.  The removed node is returned.
[DOMATTREXODUS] [DOM3CORE]

=item $node = $col->set_named_item ($node)

=item $node = $col->set_named_item_ns ($node)

Add the specified node to the list.  If there is already a node with
same name in the list, the node is removed from the list and is
returned.  Otherwise C<undef> is returned.  [DOMATTREXODUS] [DOM3CORE]
[MANAKAI]

=item $arrayref = $col->to_a

Return the new static array reference containing the nodes in the
collection.  [DOMPERL]

=item ($node1, $node2, ...) = $col->to_list

=item ($node1, $node2, ...) = @$col

Return the list of the nodes contained in the collection.  [DOMPERL]

=back

The object supports Perl standard read-only operations for array
references, e.g. C<< exists $col->[4] >>.  [DOMPERL]

=head1 SPECIFICATIONS

=over 4

=item DOMATTREXODUS

DOM Standard <view-source:http://dom.spec.whatwg.org/>.

=item DOM3CORE

Document Object Model (DOM) Level 3 Core Specification
<http://www.w3.org/TR/2004/REC-DOM-Level-3-Core-20040407/DOM3-Core.html#core-ID-1780488922>.

=item DOMPERL

manakai's DOM Perl Binding
<http://suika.fam.cx/~wakaba/wiki/sw/n/manakai%27s%20DOM%20Perl%20Binding#anchor-86>.

=item MANAKAI

manakai DOM Extensions
<http://suika.fam.cx/~wakaba/wiki/sw/n/manakai%20DOM%20Extensions>.

=back

=head1 SEE ALSO

L<Web::DOM::Node>, L<Web::DOM::Element>, L<Web::DOM::Attr>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2012 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
