=head1 NAME

Web::DOM::RootNode - The DOM |RootNode| object

=head1 DESCRIPTION

The C<Web::DOM::RootNode> class implements the DOM C<RootNode>
interface.  The C<Web::DOM::RootNode> class is an abstract class.  It
is used as subclasses such as C<Web::DOM::Element> and
C<Web::DOM::Document>.

=head1 METHODS

=over 4

=item $col = $node->children

Return the L<Web::DOM::HTMLCollection> containg the child elements of
the node.  [DOM]

=item $col = $node->get_elements_by_tag_name ($local_name)

Return the L<Web::DOM::HTMLCollection> containing the descendant
elements whose local name is equal to the argument.  If the argument
is C<*>, all descendant elements are contained.  [DOM] [MANAKAI]

=item $col = $node->get_elements_by_tag_namens ($nsurl, $local_name)

Return the L<Web::DOM::HTMLCollection> containing the descendant
elements whose namespace URL and local name matching to the specified
values.  Both namespace URL and local name arguments can be C<*>,
which represents the wildcard.  [DOM] [MANAKAI]

=item $number = $node->child_element_count

Return the number of child elements.  [DOM]

=item $child = $node->first_element_child

Return the first element child of the node.  If there is no such node,
C<undef> is returned.  [DOM]

=item $node->inner_html ($string)

=item $string = $node->inner_html

Return or set the markup representation of the content of the node.
[DOMPARSING] [HTML] [DOCUMENTINNERHTML] [MANAKAI]

If the document is an XML document and the given string is not
well-formed, the method throws an exception.

However, even if the document is an XML document and the node can't be
serialized into the well-formed XML fragment, the method does not
throw and does return an ill-formed XML fragment instead.  This is a
willful violation to the HTML Living Standard, to match current
browsers' behavior.  Future version of the module might throw an
exception if browsers start to throw an exception.

See also L<Web::DOM/DEPENDENCY>.

=item $child = $node->last_element_child

Return the last element child of the node.  If there is no such node,
C<undef> is returned.  [DOM]

=back

=head1 SPECIFICATIONS

=over 4

=item DOM

DOM Living Standard <http://dom.spec.whatwg.org/#interface-rootnode>.

=item HTML

HTML Living Standard
<http://www.whatwg.org/specs/web-apps/current-work/>.

=item DOMPARSING

DOM Parsing and Serialization <http://domparsing.spec.whatwg.org/>.

=item DOCUMENTINNERHTML

Document innerHTML
<http://html5.org/tools/web-apps-tracker?from=6531&to=6532>.

=item MANAKAI

manakai's DOM Extensions
<http://suika.fam.cx/~wakaba/wiki/sw/n/manakai++DOM%20Extensions>.

=back

=head1 SEE ALSO

L<Web::DOM::Element>, L<Web::DOM::Document>,
L<Web::DOM::DocumentFragment>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2012-2013 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
