=head1 NAME

Web::DOM::Text - The DOM |Text| object

=head1 DESCRIPTION

The C<Web::DOM::Text> class implements the DOM C<Text> interface.

=head1 METHODS

In addition to the methods of classes L<Web::DOM::Node>,
L<Web::DOM::CharacterData>, and L<Web::DOM::ChildNode>, following
methods are available:

=over 4

=item $text2 = $text1->split_text ($offset)

Split the text node into two text nodes at the specified location.
The newly created text node is returned.  [DOM]

Use of this method is discouraged.

=item $string = $text->whole_text

Return the the concatenation of the values of the text node and any
adjacent text nodes.  [DOM]

=back

=head1 SPECIFICATIONS

=over 4

=item DOM

DOM Living Standard <http://dom.spec.whatwg.org/#interface-text>.

=item DOMPERL

manakai's DOM Perl Binding
<http://suika.fam.cx/~wakaba/wiki/sw/n/manakai%27s%20DOM%20Perl%20Binding>.

=back

=head1 SEE ALSO

L<Web::DOM::Node>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2012 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
