=head1 NAME

Web::DOM::XMLDocument - The DOM |XMLDocument| object

=head1 DESCRIPTION

The C<Web::DOM::XMLDocument> class implements the DOM C<XMLDocument>
interface.  It is a subclass of the C<Web::DOM::Document> interface.

The C<Web::DOM::XMLDocument> object can be created by the
C<create_document> method of the L<Web::DOM::Implementation> object.

=head1 METHOD

In addition to the methods of the L<Web::DOM::Document> class,
following method is available:

XXX

=head1 SEE ALSO

L<Web::DOM::Document>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2012 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
